### PR TITLE
avoid redeclaration if os_alloc functions already defined

### PR DESCRIPTION
**Pull request by wizhippo**

### CODE REVIEW

**Comment by wizhippo** [comment]
Again this is only an issue when using the espressiv sdk and using the includes from this project.

**Comment by kadamski** [comment]
You mean when you take includes from esp-lwip and replace includes in SDK with them?

**Comment by wizhippo** [comment]
I had put the includes from esp-lwip directly in my project instead of using the ones from the SDK.  I had left the SDK includes where they were.  This is what caused my issue.

**Comment by kadamski** [comment]
I think I have to put some information about this on README. Right now I'm assuming SDK includes will be used but maybe I should review this assumption. Anyways, thank you for the interest in the project, hope it works for you.

**Pull request closed without merging**
